### ISSUE TITLE
Where's the Go code ?

### ISSUE THREAD

**Issue by jbrodriguez** [miguelespinoza/react-goku#2]
I see a bridge.aar, but is that all you're making available ?

This gomobile looks VERY interesting, I'm going to learn more

**Comment by miguelespinoza** [comment]
Yup in this repo I only have bridge.aar. If you look in the Architecture section of the README file. I have a link to the Go package I used (It's in another repo). In there you can see how the code is structured. 

Here's the repo: https://github.com/miguelespinoza/goku
I also have instructions in the README file on how to install from source [Using/Updating Golang:]

If you have any questions reach out to me :) It's awesome that you're interested in this

Thanks

**Comment by Gys** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  greulen@gmail.com
    Domain reulen.nl has exceeded the max emails per hour (5/5 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-ob0-f178.google.com ([209.85.214.178]:33146)
	by fyvie.footholds.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <greulen+caf_=gijs=reulen.nl@gmail.com>)
	id 1ai8eP-0003fg-DZ
	for gijs@reulen.nl; Mon, 21 Mar 2016 22:50:17 +0000
Received: by mail-ob0-f178.google.com with SMTP id xj3so17724838obb.0
        for <gijs@reulen.nl>; Mon, 21 Mar 2016 15:49:58 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=J4B8r4IVTtK0vTE3dA4Ko46r3bocY7T88PVzGTH4hVc=;
        b=VmxJd0ITFyM4zIckV30Fhaa5KDhoOQtr2hw8zE4LHgRn0grn71EAsrXWVhrsDafp/H
         aiXTb6BEePcoXl8Fjxd/BcD7VKXfNw0cMAikEI6j+l5cAmdkrzB8j05nIV6uAMGDnqUu
         KjkJSaNjb6k4dCysQ0oM+LmiPXUShZ8l3o2pV3CW+YxrmYHlR++iQ5774ZHs6NO/EDce
         pXdoLpjNYJouwip1Z8ShUegBaoqMiQ6ZBD6HKT7VXfP7M26HLfHk9ofaD+w9jrhXBSre
         21eD6/5autdOidtLjBetJFHy3EwZjbur+JboWOA4wi5hzALgaQ62J7z5hIKPKf6hZ9Cd
         qrEg==
X-Gm-Message-State: AD7BkJK7cJ6+1oqGlgwXuZNL2hxMvRyFVYfOywF+6/g8JLIzKEvg8DNTNnahkJD2WOcyDGeBZB/sbQ0RK//ZslhrB+aROnw=
X-Received: by 10.182.104.138 with SMTP id ge10mr15496544obb.81.1458600577037;
        Mon, 21 Mar 2016 15:49:37 -0700 (PDT)
X-Forwarded-To: gijs@reulen.nl
X-Forwarded-For: greulen@gmail.com gijs@reulen.nl
Delivered-To: greulen@gmail.com
Received: by 10.157.13.231 with SMTP id 94csp1206332ots;
        Mon, 21 Mar 2016 15:49:36 -0700 (PDT)
X-Received: by 10.140.159.69 with SMTP id f66mr46114630qhf.18.1458600576292;
        Mon, 21 Mar 2016 15:49:36 -0700 (PDT)
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2-ext4.iad.github.net. [192.30.252.195])
        by mx.google.com with ESMTPS id r65si25936046qha.53.2016.03.21.15.49.36
        for <greulen@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Mon, 21 Mar 2016 15:49:36 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.195 as permitted sender) client-ip=192.30.252.195;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.195 as permitted sender) smtp.mailfrom=noreply@github.com;
       dkim=pass (test mode) header.i=@github.com;
       dmarc=pass (p=NONE dis=NONE) header.from=github.com
Date: Mon, 21 Mar 2016 15:49:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458600576;
	bh=J4B8r4IVTtK0vTE3dA4Ko46r3bocY7T88PVzGTH4hVc=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1GjN7bm8mZ3iCfJ4vP9JfIdXb3sS7cNOeUzFhHygesVD1kO3HcJlwxQce+ASHbheD
	 qNKnZLSSk45HGP5BSquo/9u/CPWO4vSVTR9waoHx/UiLfUA6duXrAZoLtv5434QkwF
	 sqWlMrV1RZpaiRJLJl0rAOhqF4ahzH3vXgrq6aZE=
